trigger:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - readme.md

variables:
  solution: '**/*.sln'
  project: 'CRM_CARGADATOSCOBRANZAS_SSI.dtproj'
  buildConfiguration: 'Release'
  GroupAgent: Agentes_Compilacion
  Publish: 'CRM_CARGADATOSCOBRANZAS_SSI'
  PublishArtifact: '$(build.artifactstagingdirectory)'

pool:
  name: $(GroupAgent)
  
steps:
- task: CmdLine@2
  displayName: 'Configuration Build'
  inputs:
    script: |
      echo ----------------------------------------------------------------------------
      echo " DEBUGGING VARIABLES "
      echo ----------------------------------------------------------------------------
      echo "COMPUTER NAME:          $(COMPUTERNAME)"
      echo "DIRECTORY ARTIFACT:     $(PublishArtifact)"
      echo "DEFINITION NAME:        $(Build.DefinitionName)"
      echo "PUBLISH:                $(Publish)"
      echo "AGENT NAME:             $(Agent.Name)"
      echo "SOLUTION:               $(solution)"
      echo "BUILD CONFIGURATION:    $(buildConfiguration)"
      echo "SOURCE BRANCH NAME:     $(Build.SourceBranchName)"
      echo "BUILD NUMBER:           $(Build.BuildNumber)"
      echo "WORK DIRECTORY:         $(System.DefaultWorkingDirectory)"
      echo "TEMP DIRECTORY:         $(Agent.TempDirectory)"
      echo ----------------------------------------------------------------------------

- task: SSISBuild@0
  displayName: 'Build SSIS Project'
  inputs:
    projectPath: '$(project)'
    outputPath: '$(PublishArtifact)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: SSIS'
  inputs:
    PathtoPublish: '$(PublishArtifact)'
    ArtifactName: '$(Publish)'
